name             'sand'
maintainer       'Leo Unbekandt'
maintainer_email 'leo@scalingo.com'
license          'MIT'
issues_url       'https://github.com/Scalingo/sand-cookbook/issues'
source_url       'https://github.com/Scalingo/sand-cookbook'
chef_version     '>= 12'
supports         'ubuntu'
description      'Install SAND'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.4'
